### ISSUE TITLE
"zedenv activate" fails or makes a malformed conffile for a BE with a numerical name (systemd-boot)

### ISSUE THREAD

**Issue by TPKato** [johnramsden/zedenv#16]
"zedenv activate" fails for a BE whose name is `1`:

    # zedenv create 1
    # zedenv activate 1
    Replaced fstab entry:
    /mnt/efi/env/zedenv-BE20181130  /boot           none            rw,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro,bind   0 0
    
    With new entry:
    /mnt/efi/env/zedenv-1   /boot           none            rw,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro,bind   0 0
    
    In the boot environment's '/etc/fstab'.
    
    Would you like to edit the generated 'fstab'? [Y/n]: y
    Moved new '/etc/fstab' into place. A copy of the original '/etc/fstab' can be found at '/etc/fstab.bak'.
    
    Using existing entry zedenv-x as template taking best guess at creating one at zedenv-1.conf
    
    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/zedenv/cli/activate.py", line 369, in cli
        noop)
      File "/usr/lib/python3.7/site-packages/zedenv/cli/activate.py", line 305, in zedenv_activate
        bootloader_plugin.post_activate()
      File "/usr/lib/python3.7/site-packages/zedenv/plugins/systemdboot.py", line 327, in post_activate
        self.edit_bootloader_entry(t_esp)
      File "/usr/lib/python3.7/site-packages/zedenv/plugins/systemdboot.py", line 134, in edit_bootloader_entry
        r"\1\2\3" + self.boot_environment + r"\5")
      File "/usr/lib/python3.7/site-packages/zedenv/plugins/systemdboot.py", line 63, in __config_replace
        new_conf_list[l[0]] = re.sub(regex, regex_replace, config[l[0]])
      File "/usr/lib/python3.7/re.py", line 192, in sub
        return _compile(pattern, flags).sub(repl, string, count)
      File "/usr/lib/python3.7/re.py", line 309, in _subx
        template = _compile_repl(template, pattern)
      File "/usr/lib/python3.7/re.py", line 300, in _compile_repl
        return sre_parse.parse_template(repl, pattern)
      File "/usr/lib/python3.7/sre_parse.py", line 1018, in parse_template
        addgroup(int(this[1:]), len(this) - 1)
      File "/usr/lib/python3.7/sre_parse.py", line 962, in addgroup
        raise s.error("invalid group reference %d" % index, pos)
    re.error: invalid group reference 34 at position 5
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/bin/zedenv", line 11, in <module>
        load_entry_point('zedenv==0.3.3', 'console_scripts', 'zedenv')()
      File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
        return self.main(*args, **kwargs)
      File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
        rv = self.invoke(ctx)
      File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
        return callback(*args, **kwargs)
      File "/usr/lib/python3.7/site-packages/zedenv/cli/activate.py", line 369, in cli
        noop)
      File "/usr/lib/python3.7/site-packages/zedenv/lib/check.py", line 79, in __exit__
        if self.pidfd:
    AttributeError: 'Pidfile' object has no attribute 'pidfd'

If I create a BE `2000` and try to active it, then zedenv makes a malformed conffile:
    
    # zedenv create 2000
    # zedenv activate 2000

    Replaced fstab entry:
    (snip)
    Would you like to edit the generated 'fstab'? [Y/n]:
    Moved new '/etc/fstab' into place. A copy of the original '/etc/fstab' can be found at '/etc/fstab.bak'.
    
    Using existing entry zedenv-BE20181130 as template taking best guess at creating one at zedenv-2000.conf
    
    Replacing old entry with:
            title           Ð00] (Arch Linux)
            linux           Ð00/vmlinuz-linux
            initrd          Ð00/initramfs-linux.img
            options         zfs=zroot/ROOT/2000 rw
    .
    
    Would you like to edit the generated bootloader config? [Y/n]:
    (snip)

If I open the file with vi, I saw:

            title           \303\22000] (Arch Linux)
            linux           \303\22000/vmlinuz-linux
            initrd          \303\22000/initramfs-linux.img
            options         zfs=zroot/ROOT/2000 rw
    
Here `\303` and `\220` are a single character respectively (i.e. the first line is  `... '\303' '\220' '0' '0' ']' ...`).
I think the regular expression(s) (in `plugins/systemdboot.py` ?) does not work as you expected.

**Comment by johnramsden** [comment]
Thanks for reporting the bug. I've tracked it down to regex backreferences being ambiguous when followed by a digit. `\31` was matching group 31 instead of group 3, digit 1.
