### ISSUE TITLE
 The 'zedenv==0.3.7' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by panicketchup** [johnramsden/zedenv#22]
I opened a comment in the AUR on this issue. Let me know if you need more information. 

`$ zedenv list
Traceback (most recent call last):
  File "/usr/bin/zedenv", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'zedenv==0.3.7' distribution was not found and is required by the application`

**Comment by panicketchup** [comment]
Hello, 

It looks like it is not zedenv that is broken. There has been more issue like this with other programs. We just need to clean rebuild zedenv against python 3.8. (https://github.com/Askannz/optimus-manager/issues/174)
